---
- name: Clone Certbot into configured directory.
  git:
    repo: "{{ certbot_repo }}"
    dest: "{{ certbot_dir }}"
    version: "{{ certbot_version }}"
    update: "{{ certbot_keep_updated }}"
    force: true

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_dir }}/certbot-auto"

- name: Ensure certbot-auto is executable.
  file:
    path: "{{ certbot_script }}"
    mode: 0755

- name: Amazon - replace line in certbot auto script to make it work for Amazon Linux
  lineinfile:
    path: "{{ certbot_script }}"
    regexp: 'elif \[ -f \/etc\/redhat-release \]; then'
    line: "elif [ -f /etc/redhat-release ] || grep 'cpe:.*:amazon_linux:2' /etc/os-release > /dev/null 2>&1; then"
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'
